#ifndef RISTUX_DROPBEAR_LOCALOPTIONS_H
#define RISTUX_DROPBEAR_LOCALOPTIONS_H

#define DEBUG_TRACE 0
#define DO_MOTD 0
#define DROPBEAR_CLI_AGENTFWD 0
#define DROPBEAR_CLI_ASKPASS_HELPER 0
#define DROPBEAR_CLI_LOCALTCPFWD 0
#define DROPBEAR_CLI_NETCAT 0
#define DROPBEAR_CLI_PASSWORD_AUTH 0
#define DROPBEAR_CLI_PROXYCMD 0
#define DROPBEAR_CLI_REMOTETCPFWD 0
#define DROPBEAR_REEXEC 0
#define DROPBEAR_SFTPSERVER 0
#define DROPBEAR_SK_KEYS 0
#define DROPBEAR_SVR_AGENTFWD 0
#define DROPBEAR_SVR_LOCALSTREAMFWD 0
#define DROPBEAR_SVR_LOCALTCPFWD 0
#define DROPBEAR_SVR_PASSWORD_AUTH 1
#define DROPBEAR_SVR_REMOTESTREAMFWD 0
#define DROPBEAR_SVR_REMOTETCPFWD 0
#define DROPBEAR_USE_PASSWORD_ENV 0
#define DROPBEAR_USE_SSH_CONFIG 0
#define DROPBEAR_USER_ALGO_LIST 0

#endif
